local M = {}

M.dashboard = function()
  math.randomseed(os.time())
  local headers = {
    {
      [[          |  \ \ | |/ /                     ]],
      [[          |  |\ `' ' /                      ]],
      [[          |  ;'aorta \      / , pulmonary   ]],
      [[          | ;    _,   |    / / ,  arteries  ]],
      [[ superior | |   (  `-.;_,-' '-' ,           ]],
      [[vena cava | `,   `-._       _,-'_           ]],
      [[          |,-`.    `.)    ,<_,-'_, pulmonary]],
      [[         ,'    `.   /   ,'  `;-' _,  veins  ]],
      [[        ;        `./   /`,    \-'           ]],
      [[        | right   /   |  ;\   |\            ]],
      [[        | atrium ;_,._|_,  `, ' \           ]],
      [[        |        \    \ `       `,          ]],
      [[        `      __ `    \   left  ;,         ]],
      [[         \   ,'  `      \,  ventricle       ]],
      [[          \_(            ;,      ;;         ]],
      [[          |  \           `;,     ;;         ]],
      [[ inferior |  |`.          `;;,   ;'         ]],
      [[vena cava |  |  `-.        ;;;;,;'          ]],
      [[          |  |    |`-.._  ,;;;;;'           ]],
      [[          |  |    |   | ``';;;'  FL         ]],
      [[                  aorta                     ]],
    },
    {
      [[            ___           _,.---,---.,_                                 ]],
      [[            |         ,;~'             '~;,                             ]],
      [[            |       ,;                     ;,                           ]],
      [[   Frontal  |      ;                         ; ,--- Supraorbital Foramen]],
      [[    Bone    |     ,'                         /'                         ]],
      [[            |    ,;                        /' ;,                        ]],
      [[            |    ; ;      .           . <-'  ; |                        ]],
      [[            |__  | ;   ______       ______   ;<----- Coronal Suture     ]],
      [[           ___   |  '/~"     ~" . "~     "~\'  |                        ]],
      [[           |     |  ~  ,-~~~^~, | ,~^~~~-,  ~  |                        ]],
      [[ Maxilla,  |      |   |        }:{        | <------ Orbit               ]],
      [[Nasal and  |      |   l       / | \       !   |                         ]],
      [[Zygomatic  |      .~  (__,.--" .^. "--.,__)  ~.                         ]],
      [[  Bones    |      |    ----;' / | \ `;-<--------- Infraorbital Foramen  ]],
      [[           |__     \__.       \/^\/       .__/                          ]],
      [[              ___   V| \                 / |V <--- Mastoid Process      ]],
      [[              |      | |T~\___!___!___/~T| |                            ]],
      [[              |      | |`IIII_I_I_I_IIII'| |                            ]],
      [[     Mandible |      |  \,III I I I III,/  |                            ]],
      [[              |       \   `~~~~~~~~~~'    /                             ]],
      [[              |         \   .       . <-x---- Mental Foramen            ]],
      [[              |__         \.    ^    ./                                 ]],
      [[                            ^~~~^~~~^                                   ]],
    },
    {
      [[]],
      [[         _nnnn_                      ]],
      [[        dGGGGMMb     ,"""""""""""""".]],
      [[       @p~qp~~qMb    | Linux Rules! |]],
      [[       M|@||@) M|   _;..............']],
      [[       @,----.JM| -'                 ]],
      [[      JS^\__/  qKL                   ]],
      [[     dZP        qKRb                 ]],
      [[    dZP          qKKb                ]],
      [[   fZP            SMMb               ]],
      [[   HZM            MMMM               ]],
      [[   FqM            MMMM               ]],
      [[ __| ".        |\dS"qML              ]],
      [[ |    `.       | `' \Zq              ]],
      [[_)      \.___.,|     .'              ]],
      [[\____   )MMMMMM|   .'                ]],
      [[     `-'       `--' hjm              ]],
      [[]],
    },
  }
  return headers[math.random(1, #headers)]
end

return M
